spring.application.name=acessopuc

app.user.username=f1783574@gmail.com
app.user.password=sophiaferreira1a
app.user.name=Sophia

app.admin.username=profaramuni
app.admin.password=profaramuni
app.admin.name=Administrador
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=f1783574@gmail.com
spring.mail.password=SUA_SENHA_DE_APP_AQUI
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true